"""empty message

Revision ID: 2588e8faa752
Revises: 4dc2c11f81c2
Create Date: 2019-08-18 11:10:02.673699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2588e8faa752'
down_revision = '4dc2c11f81c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offence', sa.Column('fourth_offence', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offence', 'fourth_offence')
    # ### end Alembic commands ###
