"""empty message

Revision ID: 4dc2c11f81c2
Revises: 
Create Date: 2019-08-17 22:58:26.003181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc2c11f81c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dayrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hourlyrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=120), nullable=True),
    sa.Column('l1_rate', sa.Float(), nullable=True),
    sa.Column('l2_rate', sa.Float(), nullable=True),
    sa.Column('l3_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offence_type', sa.String(length=220), nullable=True),
    sa.Column('first_offence', sa.String(length=64), nullable=True),
    sa.Column('second_offence', sa.String(length=64), nullable=True),
    sa.Column('third_offence', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rid', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=168), nullable=True),
    sa.Column('descriptiion', sa.String(length=264), nullable=True),
    sa.Column('ado', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=8), nullable=True),
    sa.Column('munit', sa.String(length=8), nullable=True),
    sa.Column('production', sa.Float(), nullable=True),
    sa.Column('total_rate', sa.Float(), nullable=True),
    sa.Column('m_production', sa.Float(), nullable=True),
    sa.Column('m_total_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rid'),
    sa.UniqueConstraint('title')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('hour_dayrate',
    sa.Column('hourlyrate_id', sa.Integer(), nullable=True),
    sa.Column('dayrate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dayrate_id'], ['dayrate.id'], ),
    sa.ForeignKeyConstraint(['hourlyrate_id'], ['hourlyrate.id'], )
    )
    op.create_table('rate_category',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('rate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], )
    )
    op.create_table('rate_tag',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('rate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rate_id'], ['rate.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_tag')
    op.drop_table('rate_category')
    op.drop_table('hour_dayrate')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('rate')
    op.drop_table('offence')
    op.drop_table('hourlyrate')
    op.drop_table('dayrate')
    op.drop_table('category')
    # ### end Alembic commands ###
